services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: |
      corepack enable
      pnpm install
      pnpm run build
    startCommand: n8n start
    runtime: node
    nodeVersion: 20.19.0
    autoDeploy: true
    envVars:
      # --- Autenticación básica ---
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false   # (lo pondrás manualmente en Render por seguridad)

      # --- Base de datos Neon ---
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_CONNECTION_URL
        sync: false   # también la pondrás en Render

      # --- Configuración general ---
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: WEBHOOK_URL
        sync: false   # la URL la pondrás cuando Render asigne el dominio

      # --- Seguridad y optimización ---
      - key: GENERIC_TIMEZONE
        value: "Europe/Madrid"
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: "all"
      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: "all"
      - key: EXECUTIONS_DATA_PRUNE
        value: "true"
      - key: EXECUTIONS_DATA_MAX_AGE
        value: "336" # en horas = 14 días
